### ISSUE TITLE
did not work

### ISSUE THREAD

**Issue by zittox** [YasefDogan/youtube-vanced-for-android-5.1.1-update-youtube-error-FIX-for-VANCED-#1]
for my m51..  still bot able to play video 😩

**Comment by YasefDogan** [comment]
> for my m51..  still bot able to play video 😩

Yes, its not working now, because the original youtube app is stopped working on android 5  (7may 2023), thats why my modded vanced version stopped to. Its because of the original youtube's itself, stopped working, sadly i cant help you guys in this situation. If someone will make another one that is working, i will share it on that page, but sadly i cant go on for now...

**Comment by zittox** [comment]
found it  https://github.com/cuynu/ytvanced

**Comment by YasefDogan** [comment]
> found it https://github.com/cuynu/ytvanced

No those will not work for android 5, im working on android 5 spesificly, i made a working version for android 5 but it needs to magisk 24.3, working for making it easier for enduser, even if i Cant pac it i will make a guide for everyone

**Comment by YasefDogan** [comment]
> found it https://github.com/cuynu/ytvanced

hey i fixed the issue fot android 5 to, if you wanna look at it check the realeses page

**Comment by testermania** [comment]
hi;

Does playback stop after 58-60 seconds? There was such a problem under Android 7 for Vanced.

**Comment by YasefDogan** [comment]
> hi;
> 
> Does playback stop after 58-60 seconds? There was such a problem under Android 7 for Vanced.

nope its working now, but i recommend  kitadai31 's patch for androıd 6 or 7
