### ISSUE TITLE
connection server error 400

### ISSUE THREAD

**Issue by krimnassim** [YasefDogan/youtube-vanced-for-android-5.1.1-update-youtube-error-FIX-for-VANCED-#8]
Hi,can you fix youtube app connection server error 400 and thanks.

**Comment by jhosueRs** [comment]
I'm having the same issue, after clearing the app's data and cache the error is gone but I can't login to my account.       Actually there is a fix but also there isnt, İt wont be fully functional, Go to settings(your prophile photo then) > revanced settings > other options (the last option) > spoof app version and spoof the app version to 17.35.35 or 17.33.42 Shorts will work, For the normal videos You have to add them on a playlist( for example watch later press on the 3 down right left to text > click add to watch later > there will be a pop up saying go to list click on it> then you can play videos from the playlist) you have to play videos from the playlist, Otherwise it wont open the videos, videos in the main screen are not clickable. For now its the best i can do.

**Comment by Nehalemna** [comment]
Hello I'm having to same issue what's the solution?

**Comment by Nehalemna** [comment]
When I watch shorts there aren't any subscription and channel name

**Comment by Nehalemna** [comment]
Hello videos doesn't play now it says update the app

**Comment by krimnassim** [comment]
if u guys still having issues use newpipe is the only good option for 5.1.1
